services:
  - type: web
    name: lazada-playwright-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT